In [2]:
import numpy as np

In [6]:
arr = np.random.randint(1,100,size=10)
print(arr)
sort = np.sort(arr)
print(sort)
arr.sort()
print("Array is sorted in the original one ",arr)

[13  8 78 38 94 55 96 35 76  5]
[ 5  8 13 35 38 55 76 78 94 96]
Array is sorted in the original one  [ 5  8 13 35 38 55 76 78 94 96]


In [8]:
arr = np.random.randint(1,100,size=10)
print(arr)
i=np.argsort(arr)
print(i)
sorted_=arr[i]
print("Sorted via fancy",sorted_)
np.sort(arr)

[78 54  2 42 61 39 17 63 29 33]
[2 6 8 9 5 3 1 4 7 0]
Sorted via fancy [ 2 17 29 33 39 42 54 61 63 78]


array([ 2, 17, 29, 33, 39, 42, 54, 61, 63, 78])

In [10]:
np.random.seed(1)
ar =np.random.randint(19,220,size=(4,6))
print("Original Array",ar)
row_sorted= np.sort(ar,axis=0)
print("Row Sorted",row_sorted)
col_sorted= np.sort(ar,axis=1)
print("col sorted",col_sorted)

Original Array [[ 56 159  91 156 152  98]
 [211 163 148  90 153  44]
 [197  39 120 165 158 175]
 [176 161  69  87 115 105]]
Row Sorted [[ 56  39  69  87 115  44]
 [176 159  91  90 152  98]
 [197 161 120 156 153 105]
 [211 163 148 165 158 175]]
col sorted [[ 56  91  98 152 156 159]
 [ 44  90 148 153 163 211]
 [ 39 120 158 165 175 197]
 [ 69  87 105 115 161 176]]


In [12]:
np.random.seed(1)
ar =np.random.randint(1,22,size=15)
print(ar)
a1=np.partition(ar, 4)
print("3 smallest ",a1)
np.sort(ar)

[ 6 12 13  9 10 12  6 16  1 17  2 13  8 14  7]
3 smallest  [ 6  6  2  1  7 12 10 12  9 17 13 13  8 14 16]


array([ 1,  2,  6,  6,  7,  8,  9, 10, 12, 12, 13, 13, 14, 16, 17])

In [16]:
stud_name = np.array(["Nisarg","M","Rakkasagi"])
print(len(stud_name))
scores=np.array([24,35,11])
a=np.argsort(scores)
ranked_stud=stud_name[a]
print(ranked_stud)

3
['Rakkasagi' 'Nisarg' 'M']
