In [1]:
import numpy as np

In [12]:
#8
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(a)
print(a.ndim,a.shape,a.size,a.dtype)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1 (20,) 20 int32


In [30]:
#11
aa = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(aa)
print(aa[0:2, 0:2])
print(aa[:, ::2])
print(aa[:, ::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [38]:
#15
ar = np.arange(15)
print(ar)
x1,x2,x3 = np.split(ar,3)
print(x1)
print(x2)
print(x3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [64]:
#14
np.random.seed(1)
b = np.random.randint(0,10,size=(2,3))
print(b)
a= np.random.randint(0,10,size=(2,3))
print(a)
v_stack = np.vstack((b,a))
print(v_stack)
v_concat=np.concatenate((b,a),axis=0)
print(v_concat)
h_stack = np.hstack((b,a))
print(h_stack)
h_concat=np.concatenate((b,a),axis=1)
print(h_concat)

[[5 8 9]
 [5 0 0]]
[[1 7 6]
 [9 2 4]]
[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]]
[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]]
[[5 8 9 1 7 6]
 [5 0 0 9 2 4]]
[[5 8 9 1 7 6]
 [5 0 0 9 2 4]]


In [3]:
#9
import numpy as np
np.random.seed(1)
x=np.random.randint(0,50,size=(4,5))
print(x)
print(x.itemsize,x.nbytes)

[[37 43 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 45  6]
 [25 20 37 18 20]]
4 80


In [13]:
#16
np.random.seed(1)
x = np.random.randint(0,100,size=(6,4))
print("Original Array\n",x)
h1,h2=np.hsplit(x,2)
print("HSplit1\n",h1)
print("HSplit2\n",h2)
v1,v2 = np.vsplit(x,2)
print("VSplit1\n",v1)
print("VSplit2\n",v2)

Original Array
 [[37 12 72  9]
 [75  5 79 64]
 [16  1 76 71]
 [ 6 25 50 20]
 [18 84 11 28]
 [29 14 50 68]]
HSplit1
 [[37 12]
 [75  5]
 [16  1]
 [ 6 25]
 [18 84]
 [29 14]]
HSplit2
 [[72  9]
 [79 64]
 [76 71]
 [50 20]
 [11 28]
 [50 68]]
VSplit1
 [[37 12 72  9]
 [75  5 79 64]
 [16  1 76 71]]
VSplit2
 [[ 6 25 50 20]
 [18 84 11 28]
 [29 14 50 68]]


In [25]:
#10
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print("a\n",arr[1,2])
print("b\n",arr[-1])
print("c\n",arr[:,-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a
 7
b
 [ 9 10 11 12]
c
 [ 4  8 12]


In [49]:
#13
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
col_v = arr.reshape(12,1)
print(col_v)
col_ve = arr.ravel()[:, np.newaxis]
print(col_ve)
#both are identical 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [55]:
#12
m=np.array([[85, 90, 78, 92],[88, 76, 95, 89],[90, 92, 88, 94]])
print(m)


[[85 90 78 92]
 [88 76 95 89]
 [90 92 88 94]]
