In [1]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])
print(arr,type(arr))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [7]:
arr_ = np.array([[1,2],[3,4],[5,6]])
print(arr_)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
arr1 = np.array([7,8,9],dtype=float)
print(arr1,type(arr1))

[7. 8. 9.] <class 'numpy.ndarray'>


In [12]:
a = np.zeros(6)
print(a)

[0. 0. 0. 0. 0. 0.]


In [14]:
b= np.ones((3,2),dtype=int)
print(b)

[[1 1]
 [1 1]
 [1 1]]


In [16]:
c=np.empty((2,2))
print(c)
#bcoz due to present of already used values in the memory locations 
#bcoz it will be faster as it skips initialization time

[[0.00000000e+000 1.24699509e-311]
 [1.24699509e-311 1.24699509e-311]]


In [30]:
da=np.arange(0,20,2)
print(da)

[ 0  2  4  6  8 10 12 14 16 18]


In [28]:
eg=np.linspace(0,1,6)
print(eg)
#function skips the last value (exlusive)
#linspace function keeps the value(inclusive)

[0.  0.2 0.4 0.6 0.8 1. ]


In [24]:
fa=np.random.random((3,3))
print(fa)

[[0.69159997 0.65921696 0.4315403 ]
 [0.3532371  0.59544765 0.44183008]
 [0.42750977 0.47036385 0.10679115]]
